# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hats < Formula
  desc "Identity profiles for agents and shells"
  homepage "https://github.com/chrismcdermut/hats"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.0/hats_0.5.0_darwin_amd64.tar.gz"
      sha256 "5dca4c1696c3e6f8862dcf1a79c8fceb56b1c7aa669d68e840d396336a38ee66"

      define_method(:install) do
        bin.install "hats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.0/hats_0.5.0_darwin_arm64.tar.gz"
      sha256 "6f518d9ed3221bb87fde85b8f8c21b7ac3a81823d2c8795d446ec06e4323871f"

      define_method(:install) do
        bin.install "hats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.0/hats_0.5.0_linux_amd64.tar.gz"
      sha256 "39aa740e82331487403b5ab68e298b044a08730389e72c4de853e0e42eca158e"
      define_method(:install) do
        bin.install "hats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.0/hats_0.5.0_linux_arm64.tar.gz"
      sha256 "f7d5b7ec3d191fdaaddfbe547599d9088ccb5114aec369e4e2b2dc94fb949f52"
      define_method(:install) do
        bin.install "hats"
      end
    end
  end

  test do
    assert_match "identity profiles", shell_output("#{bin}/hats --help")
  end
end
