# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hats < Formula
  desc "Identity profiles for agents and shells"
  homepage "https://github.com/chrismcdermut/hats"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.2/hats_0.5.2_darwin_amd64.tar.gz"
      sha256 "896caee1cec024a4e3188bfa4273ab569c9b985cb6e3a726fa908dba12fb1c53"

      define_method(:install) do
        bin.install "hats"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.2/hats_0.5.2_darwin_arm64.tar.gz"
      sha256 "b2bc4b8de5fb9744ec5ec3175a5a1859a35268cdff3ca167005d9003ca545326"

      define_method(:install) do
        bin.install "hats"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.2/hats_0.5.2_linux_amd64.tar.gz"
      sha256 "103e518bbcb33f2513f6f118cbc14a4966e2f61416ab6d7a97f90e7e5c5f5add"
      define_method(:install) do
        bin.install "hats"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chrismcdermut/hats/releases/download/v0.5.2/hats_0.5.2_linux_arm64.tar.gz"
      sha256 "b80cab9a9ee817dcf05ff88e1690f49c5b243c01293f0f059bf02d4a88032573"
      define_method(:install) do
        bin.install "hats"
      end
    end
  end

  test do
    assert_match "identity profiles", shell_output("#{bin}/hats --help")
  end
end
